#!/bin/bash


#rm cwnd_new_1
#rm cwnd_new_2

SF1=f3a90b00
SF2=f3a91600

############# Number of pakets per subflow ###########

# less exp-4_cap-100_100_del_10-10_20-20
grep -rZ -E "subflow_selector_exit" /home/lab/new-analysis/syslog > mptcp_packets

grep -rZ -E "$SF1" mptcp_packets > packets_sf1
grep -rZ -E "$SF2" mptcp_packets > packets_sf2




grep -rZ -E "subflow_select_active" /home/lab/new-analysis/syslog > mptcp_packets_a

grep -rZ -E "$SF1" mptcp_packets_a > packets_a_asf1
grep -rZ -E "$SF2" mptcp_packets_a > packets_a_sf2





########forward delay data##############

#grep -rZ -E "tcp_cong" /home/lab/new-analysis/new-d-delay---1 > mptcp_fw_delay_1
grep -rZ -E "fw_delay" /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_fw_delay_cong

#rm mptcp_fw_delay_1

# for subflow 1

grep -rZ -E "$SF1" mptcp_fw_delay_cong > fw_delay_sf1
awk '{print $7, $12}' fw_delay_sf1 > fw_delay_sf1_new
sed 's/]//' fw_delay_sf1_new > fw_delay_new_11_cong
#sed 's/.//' fw_delay_new_111 > fw_delay_new_11
head -n -5 fw_delay_new_11_cong > fw_delay_new_1
rm fw_delay_sf1
rm fw_delay_sf1_new
#rm fw_delay_new_111
rm fw_delay_new_1

#for subflow 2

grep -rZ -E "$SF2" mptcp_fw_delay_cong > fw_delay_sf2
awk '{print $7, $12}' fw_delay_sf2 > fw_delay_sf2_new
sed 's/]//' fw_delay_sf2_new > fw_delay_new_22_cong
#sed 's/.//' fw_delay_new_222 > fw_delay_new_22
head -n -5 fw_delay_new_22_cong > fw_delay_new_2
rm fw_delay_sf2
rm fw_delay_sf2_new
#rm fw_delay_new_222
rm fw_delay_new_2


########backward delay data##############

#grep -rZ -E "tcp_cong" /home/lab/new-analysis/new-d-delay---1 > mptcp_bw_delay_1
grep -rZ -E "bw_delay" /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_bw_delay_cong

#rm mptcp_fw_delay_1

# for subflow 1

grep -rZ -E "$SF1" mptcp_bw_delay_cong > bw_delay_sf1
awk '{print $7, $12}' bw_delay_sf1 > bw_delay_sf1_new
sed 's/]//' bw_delay_sf1_new > bw_delay_new_11_cong  
#sed 's/.//' fw_delay_new_111 > fw_delay_new_11
head -n -5 bw_delay_new_11_cong > bw_delay_new_1
rm bw_delay_sf1
rm bw_delay_sf1_new
#rm fw_delay_new_111
rm bw_delay_new_1   

#for subflow 2

grep -rZ -E "$SF2" mptcp_bw_delay_cong > bw_delay_sf2
awk '{print $7, $12}' bw_delay_sf2 > bw_delay_sf2_new
sed 's/]//' bw_delay_sf2_new > bw_delay_new_22_cong  
#sed 's/.//' fw_delay_new_222 > fw_delay_new_22
head -n -5 bw_delay_new_22_cong > bw_delay_new_2
rm bw_delay_sf2
rm bw_delay_sf2_new
#rm fw_delay_new_222
rm bw_delay_new_2 

########srtt_f delay data##############

#grep -rZ -E "tcp_cong" /home/lab/new-analysis/new-d-delay---1 > mptcp_fw_delay_1
grep -rZ -E " srtt_f " /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_srtt_f_cong

#rm mptcp_fw_delay_1

# for subflow 1

grep -rZ -E "$SF1" mptcp_srtt_f_cong > srtt_f_sf1
awk '{print $7, $12}' srtt_f_sf1 > srtt_f_sf1_new
sed 's/]//' srtt_f_sf1_new > srtt_f_new_11_cong
#sed 's/.//' fw_delay_new_111 > fw_delay_new_11
head -n -5 srtt_f_new_11_cong > srtt_f_new_1
rm srtt_f_sf1
rm srtt_f_sf1_new
#rm fw_delay_new_111
rm srtt_f_new_1

#for subflow 2

grep -rZ -E "$SF2" mptcp_srtt_f_cong > srtt_f_sf2
awk '{print $7, $12}' srtt_f_sf2 > srtt_f_sf2_new
sed 's/]//' srtt_f_sf2_new > srtt_f_new_22_cong
#sed 's/.//' fw_delay_new_222 > fw_delay_new_22
head -n -5 srtt_f_new_22_cong > srtt_f_new_2
rm srtt_f_sf2
rm srtt_f_sf2_new
#rm fw_delay_new_222
rm srtt_f_new_2




############rtt data###############

grep -rZ -E "tcp_rtt_estm" /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_rtt

#for subflow 1

grep -rZ -E "$SF1" mptcp_rtt > rtt_sf1
awk '{print $7, $11}' rtt_sf1 > rtt_sf1_new
sed 's/]//' rtt_sf1_new > rtt_new_11
head -n -5 rtt_new_11 > rtt_new_1
rm rtt_sf1
rm rtt_sf1_new
rm rtt_new_1

#for subflow 2

grep -rZ -E "$SF2" mptcp_rtt > rtt_sf2
awk '{print $7, $11}' rtt_sf2 > rtt_sf2_new
sed 's/]//' rtt_sf2_new > rtt_new_22
head -n -5 rtt_new_22 > rtt_new_2
rm rtt_sf2
rm rtt_sf2_new
rm rtt_new_2

###############cwnd data###############

grep -rZ -E "tcp_out" /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_cwnd_x1
grep -rZ -E "cwnd" /home/lab/new-analysis/mptcp_cwnd_x1 > mptcp_cwnd_out
#grep -rZ -E "tcp_cong" /home/lab/new-results/delivery-delay/exp-1_cap-100_10_del_10-10_20-20 > mptcp_cwnd_x2
#grep -rZ -E "cwnd" /home/lab/new-analysis/mptcp_cwnd_x2 > mptcp_cwnd_cong

rm mptcp_cwnd_x1
#rm mptcp_cwnd_x2

########out########
# for subflow 1

grep -rZ -E "$SF1" mptcp_cwnd_out > cwnd_sf1
awk '{print $7, $12}' cwnd_sf1 > cwnd_sf1_new
sed 's/]//' cwnd_sf1_new > cwnd_new_11_out
#sed 's/.//' cwnd_new_111_out > cwnd_new_11
head -n -5 cwnd_new_11_out > cwnd_new_1
rm cwnd_sf1_new
rm cwnd_sf1
#rm cwnd_new_111
rm cwnd_new_1

#for subflow 2

grep -rZ -E "$SF2" mptcp_cwnd_out > cwnd_sf2
awk '{print $7, $12}' cwnd_sf2 > cwnd_sf2_new
sed 's/]//' cwnd_sf2_new > cwnd_new_22_out
#sed 's/.//' cwnd_new_222_out > cwnd_new_22
head -n -5 cwnd_new_22_out > cwnd_new_2
rm cwnd_sf2_new 
rm cwnd_sf2
#rm cwnd_new_222
rm cwnd_new_2

############cong#########
# for subflow 1

grep -rZ -E "$SF1" mptcp_cwnd_cong > cwnd_sf1
awk '{print $7, $12}' cwnd_sf1 > cwnd_sf1_new
sed 's/]//' cwnd_sf1_new > cwnd_new_11_cong
#sed 's/.//' cwnd_new_111 > cwnd_new_11
head -n -5 cwnd_new_11_cong > cwnd_new_1
rm cwnd_sf1_new
rm cwnd_sf1
#rm cwnd_new_111
rm cwnd_new_1   

#for subflow 2

grep -rZ -E "$SF2" mptcp_cwnd_cong > cwnd_sf2
awk '{print $7, $12}' cwnd_sf2 > cwnd_sf2_new
sed 's/]//' cwnd_sf2_new > cwnd_new_22_cong
#sed 's/.//' cwnd_new_222 > cwnd_new_22
head -n -5 cwnd_new_22_cong > cwnd_new_2
rm cwnd_sf2_new 
rm cwnd_sf2
#rm cwnd_new_222
rm cwnd_new_2  

##############in_flight data####################

grep -rZ -E "in_flight" /home/lab/new-analysis/syslog > mptcp_in_flight
#grep -rZ -E "in_flight" /home/lab/new-analysis/mptcp_in_flight_1 > mptcp_in_flight
rm mptcp_in_flight_1 
# for subflow 1

grep -rZ -E "$SF1" mptcp_in_flight > in_flight_sf1
awk '{print $7, $12}' in_flight_sf1 > in_flight_sf1_new
sed 's/]//' in_flight_sf1_new > in_flight_new_11
#sed 's/.//' in_flight_new_111 > in_flight_new_11
head -n -5 in_flight_new_11 > in_flight_new_1
rm in_flight_sf1_new
rm in_flight_sf1
#rm in_flight_new_111
rm in_flight_new_1

#for subflow 2

grep -rZ -E "$SF2" mptcp_in_flight > in_flight_sf2
awk '{print $7, $12}' in_flight_sf2 > in_flight_sf2_new
sed 's/]//' in_flight_sf2_new > in_flight_new_22
#sed 's/.//' in_flight_new_222 > in_flight_new_22
head -n -5 in_flight_new_22 > in_flight_new_2
rm in_flight_sf2_new
rm in_flight_sf2
#rm in_flight_new_222
rm in_flight_new_2

#############ssthresh data################

grep -rZ -E "tcp_cong" /home/lab/new-results/rtt/exp-4_cap-100_100_del_10-10_20-20 > mptcp_ssthresh_1
grep -rZ -E "ssthresh" /home/lab/new-analysis/mptcp_ssthresh_1 > mptcp_ssthresh
rm mptcp_ssthresh_1
# for subflow 1

grep -rZ -E "$SF1" mptcp_ssthresh > ssthresh_sf1
awk '{print $7, $12}' ssthresh_sf1 > ssthresh_sf1_new
sed 's/]//' ssthresh_sf1_new > ssthresh_new_11
#sed 's/.//' ssthresh_new_111 > ssthresh_new_11
head -n -5 ssthresh_new_11 > ssthresh_new_1
rm ssthresh_sf1_new
rm ssthresh_sf1
#rm ssthresh_new_111 
rm ssthresh_new_1
 
#for subflow 2
grep -rZ -E "$SF2" mptcp_ssthresh > ssthresh_sf2
awk '{print $7, $12}' ssthresh_sf2 > ssthresh_sf2_new
sed 's/]//' ssthresh_sf2_new > ssthresh_new_22
#sed 's/.//' ssthresh_new_222 > ssthresh_new_22
head -n -5 ssthresh_new_22 > ssthresh_new_2
rm ssthresh_sf2_new 
rm ssthresh_sf2     
#rm ssthresh_new_222 
rm ssthresh_new_2   

